import fs from 'node:fs';
import path from 'node:path';
const statuses=new Set(['proposed','approved','rejected','expired']);
export function readLedger(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
export function normalizeEntries(ledger){return Array.isArray(ledger)?ledger:(ledger.entries||[]);}
export function validateEntry(entry,now=new Date()){const issues=[];if(!entry.id) issues.push('missing id');if(!statuses.has(entry.status)) issues.push('invalid status '+entry.status);if(!entry.connector) issues.push('missing connector');if(!entry.summary) issues.push('missing summary');if(entry.status==='approved'){if(!entry.approvedBy) issues.push('approved entry missing approvedBy');if(!entry.expiresAt) issues.push('approved entry missing expiresAt');else if(new Date(entry.expiresAt).getTime()<=now.getTime()) issues.push('approved entry is expired');}return issues;}
export function auditLedger(ledger,now=new Date()){const entries=normalizeEntries(ledger);const idCounts=entries.reduce((counts,entry)=>{if(entry.id) counts[entry.id]=(counts[entry.id]||0)+1;return counts;},{});const results=entries.map((entry)=>{const issues=validateEntry(entry,now);if(entry.id&&idCounts[entry.id]>1) issues.push('duplicate id '+entry.id);return {id:entry.id,status:entry.status,connector:entry.connector,issues};});return {generatedAt:now.toISOString(),valid:results.every((r)=>r.issues.length===0),results,counts:results.reduce((a,r)=>{a[r.status]=(a[r.status]||0)+1;return a;},{})};}
export function renderSummary(audit){const lines=['# Connector Approval Ledger Summary','','Valid: '+audit.valid,'','## Counts'];for(const s of ['proposed','approved','rejected','expired']) lines.push('- '+s+': '+(audit.counts[s]||0));lines.push('','## Entries');for(const r of audit.results) lines.push('- '+r.id+': '+r.status+' '+(r.issues.length?r.issues.join('; '):'ok'));return lines.join('\n')+'\n';}
export function writeAudit(audit,outDir){fs.mkdirSync(outDir,{recursive:true});fs.writeFileSync(path.join(outDir,'approval-audit.json'),JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(path.join(outDir,'approval-summary.md'),renderSummary(audit));}
